[config]
schemaVersion = "0.0.1"

[package]
namespace = "praetoris"
name = "PraetorisClient"
versionNumber = "0.1.78"
description = "Client-side Praetoris tools for Discord linking, creative server bridges, RPC tracing, socket metrics, and RPC probes."
websiteUrl = "https://discord.gg/3aaru2VyHJ"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2333"
RandyKnapp-EpicLoot = "0.14.8"
ValheimModding-Jotunn = "2.30.1"
ValheimModding-JsonDotNET = "13.0.4"

[build]
icon = "./Assets/ServerGuide/praetoris.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/PraetorisClient.dll"
target = "./PraetorisClient.dll"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["mods"]
