<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Source/ShippingPorts/ShippingPortDepartures.cs" Link="ShippingPortDepartures.cs" />
  </ItemGroup>
</Project>
