<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Environment.props" />
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PraetorisClient"><HintPath>../../bin/Release/PraetorisClient.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
